In [3]:
#1 Write a code to find the degree of each vertex, and store it in a dictionary.

# Function to find the degree of each vertex and sort the vertices by their degree
# The degree of a vertex is the number of edges connected to it

def vertex_degrees(graph):
    degrees = {}  # Dictionary to store degree of each vertex
    for vertex in graph:
        degrees[vertex] = len(graph[vertex])  # Count of connected vertices = degree

    # Sort the vertices by their degree in descending order
    # We use the value of degrees (i.e., degree count) for sorting
    sorted_vertices = sorted(degrees, key=degrees.get, reverse=True)
    return degrees, sorted_vertices

# Example graph represented as an adjacency list
# Each key is a vertex, and the value is the list of adjacent vertices (edges)
graph = {
    'A': ['B', 'C'],          # Vertex A is connected to B and C (degree = 2)
    'B': ['A', 'C', 'D'],     # Vertex B is connected to A, C, and D (degree = 3)
    'C': ['A', 'B', 'D', 'E'],# Vertex C is connected to A, B, D, E (degree = 4)
    'D': ['B', 'C', 'E'],     # Vertex D is connected to B, C, and E (degree = 3)
    'E': ['C', 'D']           # Vertex E is connected to C and D (degree = 2)
}

# Call the function to compute degrees and sorted vertices
degrees, sorted_vertices = vertex_degrees(graph)

# Output the degrees of all vertices
print("Degrees:", degrees)

# Output the list of vertices sorted by their degree (highest to lowest)
print("Sorted Vertices:", sorted_vertices)




Degrees: {'A': 2, 'B': 3, 'C': 4, 'D': 3, 'E': 2}
Sorted Vertices: ['C', 'B', 'D', 'A', 'E']


In [ ]:
#2 Code to inter-convert 3 graph representations: adjacency list, matrix, and edge list

import numpy as np

# Convert adjacency list to adjacency matrix
def adj_list_to_matrix(adj_list):
    nodes = sorted(adj_list.keys())
    size = len(nodes)
    matrix = np.zeros((size, size), dtype=int)

    # Map each node to an index
    node_index = {node: i for i, node in enumerate(nodes)}

    # Fill matrix: mark 1 where there is an edge
    for node, neighbors in adj_list.items():
        for neighbor in neighbors:
            matrix[node_index[node]][node_index[neighbor]] = 1
    return matrix

# Convert adjacency list to edge list
def adj_list_to_edge_list(adj_list):
    edge_list = []
    for node, neighbors in adj_list.items():
        for neighbor in neighbors:
            # To avoid duplicate edges in undirected graph
            if (neighbor, node) not in edge_list:
                edge_list.append((node, neighbor))
    return edge_list

# Convert adjacency matrix back to adjacency list
def matrix_to_adj_list(matrix, nodes):
    adj_list = {node: [] for node in nodes}
    for i in range(len(nodes)):
        for j in range(len(nodes)):
            if matrix[i][j] == 1:
                adj_list[nodes[i]].append(nodes[j])
    return adj_list

# Convert edge list back to adjacency list
def edge_list_to_adj_list(edge_list):
    adj_list = {}
    for u, v in edge_list:
        if u not in adj_list:
            adj_list[u] = []
        if v not in adj_list:
            adj_list[v] = []
        adj_list[u].append(v)
        adj_list[v].append(u)  # Assuming an undirected graph
    return adj_list

# Example usage with a sample adjacency list
adj_list = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

# Convert to adjacency matrix
adj_matrix = adj_list_to_matrix(adj_list)
print("Adjacency Matrix:")
print(adj_matrix)

# Convert to edge list
edge_list = adj_list_to_edge_list(adj_list)
print("Edge List:", edge_list)

# Convert back to adjacency list from edge list
converted_adj_list = edge_list_to_adj_list(edge_list)
print("Converted Adjacency List:", converted_adj_list)

Adjacency Matrix:
[[0 1 1 0 0 0]
 [1 0 0 1 1 0]
 [1 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 1]
 [0 0 1 0 1 0]]
Edge List: [('A', 'B'), ('A', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'F'), ('E', 'F')]
Converted Adjacency List: {'A': ['B', 'C'], 'B': ['A', 'D', 'E'], 'C': ['A', 'F'], 'D': ['B'], 'E': ['B', 'F'], 'F': ['C', 'E']}


In [6]:
#3 Function to check if two vertices are adjacent in the graph

# Adjacency means there is a direct edge between the two vertices
# The graph is represented using an adjacency list
def are_adjacent(graph, v1, v2):
    if v1 in graph:  # Check if vertex v1 exists in the graph
        return v2 in graph[v1]  # Return True if v2 is in the adjacency list of v1
    return False  # If v1 is not in the graph, they can't be adjacent

# Example graph represented as an adjacency list
adj_list = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

# Example check for adjacency between vertex 'A' and vertex 'C'
v1, v2 = 'A', 'C'
print("Are", v1, "and", v2, "adjacent?", are_adjacent(adj_list, v1, v2))


Are A and C adjacent? True


In [ ]:
#4 Function to check if a graph is complete

# A complete graph is one where every node is connected to every other node
def is_complete(graph):
    nodes = list(graph.keys())  # Get all the nodes in the graph
    for node in nodes:
        # For each node, check if it's connected to all other nodes
        # A node should be connected to every node except itself
        if set(graph[node]) != set(nodes) - {node}:
            return False  # If not, the graph is not complete
    return True  # If all nodes are connected to all others, the graph is complete

# Example of a complete graph
complete_graph = {
    'A': ['B', 'C'],     # A is connected to B and C
    'B': ['A', 'C'],     # B is connected to A and C
    'C': ['A', 'B']      # C is connected to A and B
}

# Example of an incomplete graph
incomplete_graph = {
    'A': ['B'],          # A is only connected to B
    'B': ['A', 'C'],     # B is connected to A and C
    'C': ['B']           # C is only connected to B
}

# Testing the function
print("Is the complete_graph complete?", is_complete(complete_graph))
print("Is the incomplete_graph complete?", is_complete(incomplete_graph))


Is the complete_graph complete? True
Is the incomplete_graph complete? False


In [ ]:
#5 Function to check if a graph is connected

def is_connected(graph):
    visited = set()  # Set to keep track of visited nodes
    nodes = list(graph.keys())  # List of all nodes in the graph

    # Depth-First Search (DFS) to visit all connected nodes
    def dfs(node):
        if node not in visited:
            visited.add(node)
            for neighbor in graph[node]:
                dfs(neighbor)

    dfs(nodes[0])  # Start DFS from the first node in the graph

    # If the number of visited nodes equals total nodes, the graph is connected
    return len(visited) == len(nodes)

# Example of a connected graph
connected_graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D'],
    'C': ['A', 'D'],
    'D': ['B', 'C']
}

# Example of a disconnected graph
# Nodes 'A' and 'B' are in one component, 'C' and 'D' in another
# There is no path between these two components
disconnected_graph = {
    'A': ['B'],
    'B': ['A'],
    'C': ['D'],
    'D': ['C']
}

# Check connectivity for both graphs
print("Is the graph connected?", is_connected(connected_graph))  # Expected: True
print("Is the graph connected?", is_connected(disconnected_graph))  # Expected: False


Is the graph connected? True
Is the graph connected? False


In [ ]:
#6 Function to check if a given list of vertices forms a walk, trail, path, or none of these

# Walk: Sequence of vertices where each pair is connected (edges can repeat, vertices can repeat)
# Trail: Walk with no repeated edges
# Path: Trail with no repeated vertices
def check_walk_type(graph, vertices):
    edges = set()  # To track unique edges used in the sequence
    is_trail, is_path = True, True  # Flags to determine type

    # Loop through each pair of consecutive vertices
    for i in range(len(vertices) - 1):
        v1, v2 = vertices[i], vertices[i + 1]
        # If there's no edge between them, it's not a valid walk
        if v2 not in graph.get(v1, []):
            return "None"
        # If this edge was already used, it's not a path
        if (v1, v2) in edges or (v2, v1) in edges:
            is_path = False
        # Add edge to the set (treating as undirected)
        edges.add((v1, v2))

    # A trail must not repeat edges
    is_trail = len(edges) == len(vertices) - 1
    # A path must also not repeat vertices
    is_path = is_path and is_trail and len(set(vertices)) == len(vertices)

    if is_path:
        return "Path"
    if is_trail:
        return "Trail"
    return "Walk"

# Example graph represented as an adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

# Example test with a sequence of vertices
vertices_list = ['A', 'B', 'D']
print("Type:", check_walk_type(graph, vertices_list))


Type: Path


In [ ]:
#7 Function to check if a graph is a tree

# A graph is a tree if it's connected and has no cycles
def is_tree(graph):
    # Helper function to perform DFS and check for cycles
    def dfs(node, parent):
        visited.add(node)  # Mark the current node as visited
        for neighbor in graph.get(node, []):  # Traverse neighbors
            if neighbor == parent:
                continue  # Skip the parent to avoid false cycle detection
            if neighbor in visited or not dfs(neighbor, node):
                return False  # Found a cycle or disconnected part
        return True  # No issues found in this DFS path

    if not graph:
        return False  # Empty graph can't be a tree

    visited = set()
    nodes = list(graph.keys())
    if not dfs(nodes[0], None):  # Start DFS from the first node
        return False  # If DFS returns false, it's not a tree

    return len(visited) == len(nodes)  # All nodes must be visited (graph must be connected)

# Example of a graph that *is* a tree (no cycles and fully connected)
tree_graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A'],
    'D': ['B'],
    'E': ['B']
}

# Example of a graph that is *not* a tree (contains a cycle)
non_tree_graph = {
    'A': ['B', 'C'],
    'B': ['A', 'C'],
    'C': ['A', 'B']
}

# Output results
print("Is the graph a tree?", is_tree(tree_graph))
print("Is the graph a tree?", is_tree(non_tree_graph))


Is the graph a tree? True
Is the graph a tree? False


In [ ]:
#8 Function to find a spanning tree of a connected cyclic graph

# using Depth-First Search (DFS)
def find_spanning_tree(graph):
    spanning_tree = {}  # Dictionary to store the resulting spanning tree
    visited = set()     # Set to keep track of visited nodes
    edges = []          # List to store edges included in the spanning tree

    # Inner DFS function to explore the graph
    def dfs(node):
        visited.add(node)  # Mark current node as visited
        for neighbor in graph.get(node, []):
            if neighbor not in visited:
                edges.append((node, neighbor))  # Add edge to the spanning tree
                dfs(neighbor)  # Recursively visit the neighbor

    # Start DFS from the first node in the graph
    start_node = list(graph.keys())[0]
    dfs(start_node)

    # Convert the list of edges into adjacency list form for the spanning tree
    for u, v in edges:
        if u not in spanning_tree:
            spanning_tree[u] = []
        if v not in spanning_tree:
            spanning_tree[v] = []
        spanning_tree[u].append(v)
        spanning_tree[v].append(u)

    return spanning_tree

# Example cyclic and connected graph
graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

# Generate the spanning tree
spanning_tree = find_spanning_tree(graph)
print("Spanning Tree:", spanning_tree)


Spanning Tree: {'A': ['B'], 'B': ['A', 'D', 'E'], 'D': ['B'], 'E': ['B', 'F'], 'F': ['E', 'C'], 'C': ['F']}


In [2]:
#9 Given a tree, find the number of leaf nodes.

# Function to count the number of leaf nodes in a tree
# A leaf node is a node that is connected to only one other node (degree = 1)
def count_leaf_nodes(tree):
    count = 0  # Initialize counter for leaf nodes
    for node in tree:
        # If a node has only one neighbor, it's a leaf node
        if len(tree[node]) == 1:
            count += 1
    return count  # Return the total number of leaf nodes

# Example tree represented as an adjacency list
# Each key is a node and its value is a list of connected nodes
tree = {
    'A': ['B', 'C'],      # A connects to B and C
    'B': ['A', 'D', 'E'], # B connects to A, D, and E
    'C': ['A'],           # C connects to A (leaf)
    'D': ['B'],           # D connects to B (leaf)
    'E': ['B']            # E connects to B (leaf)
}

# Output the number of leaf nodes in the tree
print("Number of leaf nodes:", count_leaf_nodes(tree))



Number of leaf nodes: 3


In [3]:
#10 Given a tree, check if it's a binary tree.

# Function to check if the tree is a binary tree
# A binary tree is a tree where no node has more than two children
# In the adjacency list, that means any node (except the root) should connect to at most 3 nodes
# because one edge goes back to the parent and the rest are children
def is_binary_tree(tree):
    for node in tree:
        if len(tree[node]) > 3:
            # More than 3 means the node has more than 2 children (considering one is the parent)
            return False
    return True

# Example tree represented as an adjacency list
# Each key is a node and its value is a list of connected nodes
tree = {
    'A': ['B', 'C'],      # A connects to B and C
    'B': ['A', 'D', 'E'], # B connects to A, D, and E
    'C': ['A'],           # C connects to A (leaf)
    'D': ['B'],           # D connects to B (leaf)
    'E': ['B']            # E connects to B (leaf)
}

# Output the number of leaf nodes in the tree
print("Number of leaf nodes:", count_leaf_nodes(tree))

# Check and output whether the tree is a binary tree or not
print("Is the tree a binary tree?", is_binary_tree(tree))

Number of leaf nodes: 3
Is the tree a binary tree? True


In [4]:
#11 Given a tree, find its height


# Function to find the height of the tree
# Height is defined as the number of edges on the longest path from the root to a leaf node
def find_tree_height(tree, root):
    visited = set()  # To track visited nodes and avoid cycles

    def dfs(node):
        visited.add(node)
        heights = []
        for neighbor in tree[node]:
            if neighbor not in visited:
                heights.append(dfs(neighbor))
        # If no children, height is 0; else height is max height of subtree + 1
        return 0 if not heights else 1 + max(heights)

    return dfs(root)

# Example tree represented as an adjacency list
# Each key is a node and its value is a list of connected nodes
tree = {
    'A': ['B', 'C'],      # A connects to B and C
    'B': ['A', 'D', 'E'], # B connects to A, D, and E
    'C': ['A'],           # C connects to A (leaf)
    'D': ['B'],           # D connects to B (leaf)
    'E': ['B']            # E connects to B (leaf)
}

# Output the number of leaf nodes in the tree
print("Number of leaf nodes:", count_leaf_nodes(tree))

# Check and output whether the tree is a binary tree or not
print("Is the tree a binary tree?", is_binary_tree(tree))

# Output the height of the tree from root 'A'
print("Height of the tree:", find_tree_height(tree, 'A'))

Number of leaf nodes: 3
Is the tree a binary tree? True
Height of the tree: 2


In [ ]:
#12 Function to find the depth of a given node from the root

# Depth is defined as the number of edges from the root to that specific node
def find_node_depth(tree, root, target):
    visited = set()

    def dfs(node, depth):
        if node == target:
            return depth  # Found the target node, return its depth
        visited.add(node)
        for neighbor in tree[node]:
            if neighbor not in visited:
                result = dfs(neighbor, depth + 1)
                if result != -1:
                    return result  # Return depth if target is found in recursion
        return -1  # If node not found

    return dfs(root, 0)

# Function to count the number of leaf nodes in a tree
def count_leaf_nodes(tree):
    count = 0
    for node, neighbors in tree.items():
        if len(neighbors) == 1:  # Leaf node has only one connection
            count += 1
    return count

# Function to check if a tree is a binary tree
# A binary tree means no node has more than two children (excluding back edge to parent)
def is_binary_tree(tree):
    for node in tree:
        # For the root node, it can have at most 2 children
        # For other nodes, one of the edges is to the parent, so it can have at most 3 edges
        if len(tree[node]) > 3:
            return False
    return True

# Function to find the height of a tree (max depth from root)
def find_tree_height(tree, root):
    visited = set()

    def dfs(node):
        visited.add(node)
        max_depth = 0
        for neighbor in tree[node]:
            if neighbor not in visited:
                depth = dfs(neighbor)
                max_depth = max(max_depth, depth)
        return max_depth + 1  # Include current node

    return dfs(root) - 1  # Subtract 1 to get height in terms of edges

# Example tree represented as an adjacency list
# Each key is a node and its value is a list of connected nodes
tree = {
    'A': ['B', 'C'],      # A connects to B and C
    'B': ['A', 'D', 'E'], # B connects to A, D, and E
    'C': ['A'],           # C connects to A (leaf)
    'D': ['B'],           # D connects to B (leaf)
    'E': ['B']            # E connects to B (leaf)
}

# Output the number of leaf nodes in the tree
print("Number of leaf nodes:", count_leaf_nodes(tree))

# Check and output whether the tree is a binary tree or not
print("Is the tree a binary tree?", is_binary_tree(tree))

# Output the height of the tree from root 'A'
print("Height of the tree:", find_tree_height(tree, 'A'))

# Output the depth of a specific node from root 'A'
print("Depth of node 'D':", find_node_depth(tree, 'A', 'D'))

Number of leaf nodes: 3
Is the tree a binary tree? True
Height of the tree: 2
Depth of node 'D': 2
